In [2]:
import numpy as np

class Matriz:
    def __init__(self, matriz):
        self.matriz = matriz

    def __str__(self):
        return str(self.matriz)

    def determinante(self):
        return np.linalg.det(self.matriz)

    def inversa(self):
        return np.linalg.inv(self.matriz)

    def transpuesta(self):
        return np.transpose(self.matriz)

    def rotacion(self, angulo):
        rad = np.radians(angulo)
        matriz_rotacion = np.array([[np.cos(rad), -np.sin(rad)],
                                    [np.sin(rad), np.cos(rad)]])
        return np.dot(matriz_rotacion, self.matriz)

class MatrizOperaciones(Matriz):
    def __init__(self, matriz):
        super().__init__(matriz)

    def determinante(self):
        return super().determinante()

    def inversa(self):
        return super().inversa()

    def transpuesta(self):
        return super().transpuesta()

    def rotacion(self, angulo):
        return super().rotacion(angulo)

# Ejemplo de uso
matriz = np.array([[8, 9],
                   [7, 5]])

mat = MatrizOperaciones(matriz)
print("Matriz original:")
print(mat)
print("Determinante:", mat.determinante())
print("Inversa:")
print(mat.inversa())
print("Transpuesta:")
print(mat.transpuesta())
print("Matriz rotada 56 grados:")
print(mat.rotacion(56))


Matriz original:
[[8 9]
 [7 5]]
Determinante: -23.0
Inversa:
[[-0.2173913   0.39130435]
 [ 0.30434783 -0.34782609]]
Transpuesta:
[[8 7]
 [9 5]]
Matriz rotada 56 grados:
[[-1.32971978  0.88754827]
 [10.5466509  10.25730267]]
